# Rename this file to languages.toml to enable multilingual support

[fr]
languageName = "French"
languagedirection = "ltr"
title = "Jaybird1291"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Jaybird1291"
weight = 2

[ja]
languageName = "Japanese"
languagedirection = "ltr"
title = "Jaybird1291"
weight = 3
